# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Build specific stats linked to reviews

Resources:
    BuildMatchStatsQueue:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: build-match-stats-queue
            VisibilityTimeout: 601
    BuildMatchStatsSqsQueuePolicy:
        Type: AWS::SQS::QueuePolicy
        Properties:
            PolicyDocument:
                Version: '2012-10-17'
                Id: BuildMatchStatsQueuePolicy
                Statement:
                    - Sid: Allow-SNS-SendMessage
                      Effect: Allow
                      Principal:
                          AWS: '*'
                      Action:
                          - sqs:SendMessage
                      Resource: !GetAtt BuildMatchStatsQueue.Arn
                      Condition:
                          ArnEquals:
                              aws:SourceArn: arn:aws:sns:us-west-2:478062583808:review-published
            Queues:
                - !Ref BuildMatchStatsQueue
    SnsSubscription:
        Type: AWS::SNS::Subscription
        Properties:
            Protocol: SQS
            Endpoint: !GetAtt BuildMatchStatsQueue.Arn
            TopicArn: arn:aws:sns:us-west-2:478062583808:review-published

    ProcessSaveMatchStatsFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: process-save-match-stats.default
            Runtime: nodejs12.x
            CodeUri: ./dist/process-save-match-stats
            MemorySize: 450
            ReservedConcurrentExecutions: 10
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - SecretsManagerReadWrite
                - AmazonSESFullAccess
                - AmazonSQSFullAccess
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: process-save-match-stats
            Timeout: 60
            Events:
                SQSEvent:
                    Type: SQS
                    Properties:
                        Queue: !GetAtt BuildMatchStatsQueue.Arn
    # ProcessSaveMatchStatsFunctionLogGroup:
    #     Type: 'AWS::Logs::LogGroup'
    #     DependsOn: 'ProcessSaveMatchStatsFunction'
    #     Properties:
    #         RetentionInDays: 7
    #         LogGroupName: !Join ['', ['/aws/lambda/', !Ref ProcessSaveMatchStatsFunction]]
